# encoding: utf-8
source 'https://rubygems.org'

gem 'inspec'
gem 'pry'
gem 'rb-readline'
gem 'forgery'
gem 'terminal-table'
gem 'thor'
gem 'colorize'
gem 'pg'
gem 'activesupport', '>= 6.1.7.1'
gem 'concurrent-ruby'
